# Refer to the documentation for the schema of this file ->
# Replace this with "config.yml" to boot-up Arisu.

# If we should enable the /register to new users.
# If this is disabled, navigate to /admin/users to add a user
registrations: false

# The enviroment to use
# default: "production"
environment: 'development'

# Sentry DSN URI to connect to Sentry to provide error handling
sentry_dsn: null

# The port to use to connect to the API and UI
# Default: 17903
port: 17903

# The host to connect to with the API and UI
# Default: '0.0.0.0'
host: '0.0.0.0'
