name: ESLint
on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - LICENSE
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - uses: actions/checkout@v1
        name: Setup repository
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global packages
        run: npm i -g eslint
      - name: Install dependencies
        run: npm i
      - name: Lints the repository
        run: npm run lint