name: ktlint
on:
  push:
    branches:
      - 'feature/**'
      - 'issue/**'
      - master
      - dev
    paths-ignore:
      - '.github/**'
      - '.cache/**'
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - '**.md'
      - 'config.example.yml'
      - 'docs/**'
      - 'renovate.json'
  pull_request:
    branches:
      - 'feature/**'
      - 'issue/**'
      - master
      - dev
    paths-ignore:
      - '.github/**'
      - '.cache/**'
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - '**.md'
      - 'config.example.yml'
      - 'docs/**'
      - 'renovate.json'
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant the machine with execution permissions
        run: chmod +x gradlew

      - name: Runs `ktlint` for any code checking
        run: ./gradlew spotlessApply

      - name: Compiles the project for any compilation errors
        run: ./gradlew build
